title: Mulberry News
email: janlukas.else@gmail.com
description: >
  The first news App from Mulberry Inc
baseurl: ""
url: "https://appydroid.tk" # for production
# url: "http://127.0.0.1:4000" # for local development

header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

disqus: true
disqus_shortname: 'appydroidtk'

# Build settings
permalink: /:title
markdown: redcarpet
include: [_pages]
exclude: [_site]
sass:
  style: compressed
future: true
timezone: Europe/Berlin
